######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 31 16:06:56 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += io.cpp
