######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 10 19:26:48 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h stringlistmodel.h
SOURCES += main.cpp mainwindow.cpp stringlistmodel.cpp
