######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 10 19:00:09 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mapwidget.h
SOURCES += main.cpp mapwidget.cpp
