######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 30 16:00:05 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myclass.h
SOURCES += main.cpp myclass.cpp
