######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 1 15:18:41 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qtestlib

# Input
HEADERS += progress.h
SOURCES += main.cpp progress.cpp
