######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 3 15:34:08 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += geometry.h
SOURCES += geometry.cpp main.cpp
