######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 1 18:09:33 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += qtcpcli.h
SOURCES += main.cpp qtcpcli.cpp
