######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 11 10:19:53 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mouseevent.h
SOURCES += main.cpp mouseevent.cpp
