######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 7 14:37:48 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += baseinfo.h configdialog.h contact.h detail.h fader.h
SOURCES += baseinfo.cpp \
           configdialog.cpp \
           contact.cpp \
           detail.cpp \
           fader.cpp \
           main.cpp
