######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 8 19:49:53 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qtestlib

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
