######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 3 19:39:22 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += messagebox.h
SOURCES += main.cpp messagebox.cpp
