######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 10 19:33:25 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += networkinformation.h
SOURCES += main.cpp networkinformation.cpp
