######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 5 14:46:00 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywidget.h
FORMS += first.ui second.ui third.ui
SOURCES += main.cpp mywidget.cpp
