######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 11 10:47:30 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stringcodec.h
SOURCES += main.cpp stringcodec.cpp
