######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 8 20:23:49 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += printimage.h
SOURCES += main.cpp printimage.cpp
