######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 1 18:10:54 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += qtcpser.h
SOURCES += main.cpp qtcpser.cpp
