######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 11 09:49:40 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += server.h tcpclientsocket.h tcpserver.h
SOURCES += main.cpp server.cpp tcpclientsocket.cpp tcpserver.cpp
