######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 10 19:06:55 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += items.h mainwidget.h
SOURCES += items.cpp main.cpp mainwidget.cpp
