######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 11 10:10:11 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fileinformation.h
SOURCES += fileinformation.cpp main.cpp
