######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 9 08:18:55 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imgprocessor.h
SOURCES += imgprocessor.cpp main.cpp
