######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 11 09:38:38 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += udpclient.h
SOURCES += main.cpp udpclient.cpp
