######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 11 10:37:08 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cursor.h
SOURCES += cursor.cpp main.cpp
