######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 10 18:52:44 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += pictrans.h
SOURCES += main.cpp pictrans.cpp
