######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 8 19:43:43 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += digiclock.h
SOURCES += digiclock.cpp main.cpp
