######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 8 20:12:14 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += printtext.h
SOURCES += main.cpp printtext.cpp
