######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 5 14:02:16 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += table.h
SOURCES += main.cpp table.cpp
