######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 10 19:28:14 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += combodelegate.h datedelegate.h spindelegate.h
SOURCES += combodelegate.cpp datedelegate.cpp main.cpp spindelegate.cpp
