######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 10 19:05:26 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += graphicsitem.h mainwidget.h
SOURCES += graphicsitem.cpp main.cpp mainwidget.cpp
