######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 10 18:53:52 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += rubberband.h
SOURCES += main.cpp rubberband.cpp
