######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 4 09:51:47 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myform.h
SOURCES += main.cpp myform.cpp
