######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 11 10:23:22 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += keyevent.h
SOURCES += keyevent.cpp main.cpp
