######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 11 10:26:17 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += eventfilter.h
SOURCES += eventfilter.cpp main.cpp
