######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 3 16:22:27 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += inputdialog.h
SOURCES += inputdialog.cpp main.cpp
