######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 3 11:20:58 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
CONFIG += qtestlib

# Input
HEADERS += qtcpcli.h
FORMS += form.ui
SOURCES += main.cpp qtcpcli.cpp
