######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 5 20:13:04 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stack.h
SOURCES += main.cpp stack.cpp
