######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 4 17:45:22 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myform.h stone.h
SOURCES += main.cpp myform.cpp stone.cpp
