######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 11 10:39:58 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += style.h
SOURCES += main.cpp style.cpp
