######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 11 10:42:45 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dragicon.h dragwidget.h
SOURCES += dragicon.cpp dragwidget.cpp main.cpp
