######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 10 19:22:11 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
