######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 10 18:51:06 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += drawwidget.h painter.h
SOURCES += drawwidget.cpp main.cpp painter.cpp
