######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 7 11:35:41 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += palette.h
SOURCES += main.cpp palette.cpp
