######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 1 15:03:15 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += standarddialogs.h
SOURCES += main.cpp standarddialogs.cpp
