######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 11 09:37:28 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += udpserver.h
SOURCES += main.cpp udpserver.cpp
