######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 5 14:43:58 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += name.ui
SOURCES += main.cpp
