######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 2 15:32:49 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qtestlib
QT += network

# Input
HEADERS += myform.h
FORMS += form.ui
SOURCES += main.cpp myform.cpp
