######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 1 11:20:00 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
