######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 31 09:37:19 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += teamleadersdialog.h
SOURCES += main.cpp teamleadersdialog.cpp
