######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 5 14:47:49 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . forms
INCLUDEPATH += .
CONFIG += uitools

# Input
HEADERS += mywidget.h
FORMS += first.ui second.ui forms/third.ui
SOURCES += main.cpp mywidget.cpp
