######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 6 10:55:10 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += extension.h
SOURCES += extension.cpp main.cpp
