######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 11 10:32:24 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += pararw.h
SOURCES += main.cpp pararw.cpp
