######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 5 15:03:27 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += layoutdlg.h
SOURCES += layoutdlg.cpp main.cpp
