######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 9 08:41:49 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fontset.h
SOURCES += fontset.cpp main.cpp
