######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 11 09:57:23 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += httpclient.h
SOURCES += httpclient.cpp main.cpp
