######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 9 08:53:37 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += listalign.h
SOURCES += listalign.cpp main.cpp
