######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 8 19:37:28 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += shapewidget.h
SOURCES += main.cpp shapewidget.cpp
