######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 11 09:50:32 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += tcpclient.h
SOURCES += main.cpp tcpclient.cpp
