######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 11 10:45:28 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += draglabel.h dragwidget.h
SOURCES += draglabel.cpp dragwidget.cpp main.cpp
