######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 6 10:27:06 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += baseinfo.h contact.h content.h detail.h
SOURCES += baseinfo.cpp contact.cpp content.cpp detail.cpp main.cpp
