######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 10 18:03:54 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h svgwidget.h svgwindow.h
SOURCES += main.cpp mainwindow.cpp svgwidget.cpp svgwindow.cpp
TRANSLATIONS += svg_zh.ts
