######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 11 10:30:09 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += settings.h
SOURCES += main.cpp settings.cpp
