######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 10 18:27:24 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwidget.h paintarea.h
SOURCES += main.cpp mainwidget.cpp paintarea.cpp
