######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 5 19:55:32 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dockwindows.h
SOURCES += dockwindows.cpp main.cpp
