######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 11 10:15:04 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fileviewer.h
SOURCES += fileviewer.cpp main.cpp
