######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 11 10:03:49 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += ftpclient.h
SOURCES += ftpclient.cpp main.cpp
