######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 9 08:30:30 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += toolbar.h
SOURCES += main.cpp toolbar.cpp
