######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 3 20:38:38 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += drawer.h
SOURCES += drawer.cpp main.cpp
